---
title: "Tables"
output: bookdown::pdf_book
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
options(knitr.table.format = "latex")
load("ERFOutput/narrow_error_table.RData")
load("ERFOutput/main_error_table.RData")
load("ERFOutput/narrow_dm_test_table.RData")
load("ERFOutput/dm_test_table.RData")

```

```{r table1-output, echo=FALSE}
table <- kable(Table, booktabs = TRUE, 
               caption = "Entire Sample Model Errors") %>%
  kable_styling(latex_options = c("striped", "scale_down"))

table
```

```{r table2-output, echo=FALSE}
table <- kable(error_table, booktabs = TRUE, 
               caption = "Policy Change Sample Model Errors") %>%
  kable_styling(latex_options = c("striped", "scale_down"))

table
```

```{r table3-output, echo=FALSE}
table <- kable(dm_test, booktabs = TRUE,
               caption = "Entire Sample Models Diebold Mariano Tests") %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>%
  footnote(general = "Positive values indicate the Model in the column is better. P-values in parentheses.",
           general_title = "Notes:",
           footnote_as_chunk = T)

table
```

```{r table4-output, echo=FALSE}
table <- kable(narrow_dm_test, booktabs = TRUE,
               caption = "Policy Change Sample Models Diebold Mariano Tests") %>%
  kable_styling(latex_options = c("striped", "scale_down")) %>%
  footnote(general = "Positive values indicate the Model in the column is better. P-values in parentheses.",
           general_title = "Notes:",
           footnote_as_chunk = T)

table
```